/** @type {import('tailwindcss').Config} */
const ch = (v) => `rgb(var(${v}) / <alpha-value>)`;

export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        ink: ch('--ink'),
        nav: ch('--nav'),
        panel: ch('--panel'),
        'panel-2': ch('--panel-2'),
        rule: ch('--rule'),
        'rule-strong': ch('--rule-strong'),
        text: ch('--text'),
        'text-2': ch('--text-2'),
        'text-3': ch('--text-3'),
        signal: ch('--signal'),
        'signal-ink': ch('--signal-ink'),
        ledger: ch('--ledger'),
        redline: ch('--redline'),
        info: ch('--info'),
        attention: ch('--attention'),
        focus: ch('--focus'),
      },
      fontFamily: {
        ui: ['Aptos', 'Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '15px', letterSpacing: '0.02em' }],
        xs: ['12px', { lineHeight: '17px' }],
        sm: ['13px', { lineHeight: '19px' }],
        base: ['14px', { lineHeight: '21px' }],
        md: ['15px', { lineHeight: '22px' }],
        lg: ['18px', { lineHeight: '26px' }],
        xl: ['24px', { lineHeight: '30px', letterSpacing: '-0.02em' }],
        '2xl': ['30px', { lineHeight: '35px', letterSpacing: '-0.025em' }],
        '3xl': ['40px', { lineHeight: '43px', letterSpacing: '-0.035em' }],
        '4xl': ['54px', { lineHeight: '56px', letterSpacing: '-0.045em' }],
      },
      borderRadius: { DEFAULT: '8px', sm: '6px', md: '10px', lg: '14px' },
      boxShadow: {
        token: 'var(--shadow)',
        'token-lg': 'var(--shadow-lg)',
        'token-xs': 'var(--shadow-xs)',
      },
      spacing: { rail: '98px', tape: '46px' },
      keyframes: {
        'fade-up': { from: { opacity: 0, translate: '0 3px' }, to: { opacity: 1, translate: '0 0' } },
        'scale-in': { from: { opacity: 0, scale: '0.985' }, to: { opacity: 1, scale: '1' } },
        'page-enter': { from: { opacity: 0, translate: '0 7px' }, to: { opacity: 1, translate: '0 0' } },
        'slide-in-left': { from: { opacity: 0, translate: '-18px 0' }, to: { opacity: 1, translate: '0 0' } },
        'slide-in-right': { from: { opacity: 0, translate: '18px 0' }, to: { opacity: 1, translate: '0 0' } },
        'fade-in': { from: { opacity: 0 }, to: { opacity: 1 } },
        'command-in': { from: { opacity: 0, translate: '0 -10px', scale: '.975' }, to: { opacity: 1, translate: '0 0', scale: '1' } },
        'notification-in': { from: { opacity: 0, translate: '0 -8px', scale: '.98' }, to: { opacity: 1, translate: '0 0', scale: '1' } },
        'bell-ring': {
          '0%, 55%, 100%': { rotate: '0deg' },
          '65%': { rotate: '13deg' },
          '75%': { rotate: '-10deg' },
          '85%': { rotate: '6deg' },
        },
        blink: { '0%,49%': { opacity: 1 }, '50%,100%': { opacity: 0.25 } },
      },
      animation: {
        'fade-up': 'fade-up .18s ease-out both',
        'scale-in': 'scale-in .14s ease-out both',
        'page-enter': 'page-enter .24s cubic-bezier(.22,.8,.32,1) both',
        'slide-in-left': 'slide-in-left .2s cubic-bezier(.22,.8,.32,1) both',
        'slide-in-right': 'slide-in-right .2s cubic-bezier(.22,.8,.32,1) both',
        'fade-in': 'fade-in .16s ease-out both',
        'command-in': 'command-in .22s cubic-bezier(.16,1,.3,1) both',
        'notification-in': 'notification-in .2s cubic-bezier(.16,1,.3,1) both',
        'bell-ring': 'bell-ring 2.8s ease-in-out infinite',
        blink: 'blink 1.6s steps(1) infinite',
      },
    },
  },
  plugins: [],
};
