/**
 * Records the walkthrough videos by driving the real application.
 *
 * Not a screen-capture of a mockup and not an animation pretending to be the product: these are
 * recordings of Vantage actually running, seeded with plausible data, with a real cursor clicking
 * real controls. If a walkthrough here breaks, it is because the product changed — which is the
 * point, and is why these are regenerated rather than filmed once and left to rot.
 *
 * The step list is the single source for three things at once: what the browser does, the caption
 * burned into the frame, and the WebVTT track. They cannot drift apart because they are the same
 * array. A caption describing a click that no longer happens is not possible here.
 *
 * Silent by design. Nobody watches a tutorial with sound on at a desk in an open office, and a
 * voice track cannot be regenerated by a script, so the captions do the narrating.
 */

import { chromium } from 'playwright';
import { spawn, spawnSync } from 'node:child_process';
import { mkdirSync, readdirSync, renameSync, rmSync, existsSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'public', 'videos');
const WORK = join(ROOT, '.video-work');
const FFMPEG = process.env.VANTAGE_FFMPEG || '/opt/pw-browsers/ffmpeg-1011/ffmpeg-linux';
const CHROME = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE
  || (existsSync('/opt/pw-browsers/chromium-1194/chrome-linux/chrome') ? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' : undefined);

export const SIZE = { width: 1280, height: 720 };

/* ── the caption bar ────────────────────────────────────────────────────────────────────────────
   Injected into the page rather than composited afterwards, so it survives the re-encode and needs
   no subtitle burn-in step. It sits above everything and never takes pointer events, so it cannot
   change what the walkthrough is demonstrating. */
const OVERLAY_CSS = `
#vantage-cap {
  position: fixed; left: 0; right: 0; bottom: 0; z-index: 2147483647;
  padding: 18px 28px 22px; pointer-events: none;
  font: 500 19px/1.45 Inter, ui-sans-serif, system-ui, sans-serif; letter-spacing: -0.01em;
  color: #fff; background: linear-gradient(to top, rgba(6,17,33,.94) 45%, rgba(6,17,33,0));
  transition: opacity 260ms ease; opacity: 0;
}
#vantage-cap.on { opacity: 1; }
#vantage-cap b { display: block; font-size: 12px; font-weight: 700; letter-spacing: .14em;
  text-transform: uppercase; color: #5fd6c6; margin-bottom: 5px; }
#vantage-cursor {
  position: fixed; z-index: 2147483646; width: 22px; height: 22px; margin: -11px 0 0 -11px;
  border-radius: 50%; pointer-events: none; background: rgba(37,99,235,.28);
  box-shadow: 0 0 0 2px rgba(37,99,235,.85), 0 2px 10px rgba(6,17,33,.35);
  transition: transform 90ms linear; opacity: 0;
}
#vantage-cursor.on { opacity: 1; }
#vantage-cursor.tap { animation: vantage-tap 420ms ease-out; }
@keyframes vantage-tap { 0% { transform: scale(1); } 45% { transform: scale(2.1); opacity: .5; } 100% { transform: scale(1); } }
`;

/** Paints a caption into the bar. Kept separate from the step loop so a navigation can repaint it. */
async function paintCaption(page, current) {
  if (!current) return;
  await page.evaluate(({ eyebrow, caption }) => {
    const el = document.getElementById('vantage-cap');
    if (!el) return;
    el.innerHTML = '';
    if (eyebrow) { const b = document.createElement('b'); b.textContent = eyebrow; el.appendChild(b); }
    el.appendChild(document.createTextNode(caption));
    el.classList.add('on');
  }, current).catch(() => {});
}

async function installOverlay(page) {
  await page.addStyleTag({ content: OVERLAY_CSS }).catch(() => {});
  await page.evaluate(() => {
    if (document.getElementById('vantage-cap')) return;
    const cap = document.createElement('div');
    cap.id = 'vantage-cap';
    document.body.appendChild(cap);
    const cur = document.createElement('div');
    cur.id = 'vantage-cursor';
    document.body.appendChild(cur);
  });
}

/**
 * A soft pointer that viewers can follow.
 *
 * Playwright's real mouse leaves no trace in a recording — the cursor is composited by the OS, not
 * the page — so a click looks like the UI reacting to nothing. This draws one, and moves it in
 * steps rather than teleporting, because an instant jump reads as a cut rather than as a person.
 */
async function glideTo(page, selector) {
  const box = await page.locator(selector).first().boundingBox();
  if (!box) return null;
  const to = { x: box.x + box.width / 2, y: box.y + box.height / 2 };
  await page.evaluate(({ x, y }) => {
    const c = document.getElementById('vantage-cursor');
    if (!c) return;
    c.classList.add('on');
    c.style.left = `${x}px`;
    c.style.top = `${y}px`;
  }, to);
  await page.mouse.move(to.x, to.y, { steps: 12 });
  await page.waitForTimeout(220);
  return to;
}

async function tapMark(page) {
  await page.evaluate(() => {
    const c = document.getElementById('vantage-cursor');
    if (!c) return;
    c.classList.remove('tap');
    void c.offsetWidth;
    c.classList.add('tap');
  });
  await page.waitForTimeout(160);
}

const vtt = (s) => {
  const ms = Math.max(0, Math.round(s * 1000));
  const h = String(Math.floor(ms / 3600000)).padStart(2, '0');
  const m = String(Math.floor((ms % 3600000) / 60000)).padStart(2, '0');
  const sec = String(Math.floor((ms % 60000) / 1000)).padStart(2, '0');
  return `${h}:${m}:${sec}.${String(ms % 1000).padStart(3, '0')}`;
};

/**
 * Runs one walkthrough and writes `<id>.webm` plus `<id>.vtt`.
 *
 * `steps` is an array of { eyebrow, caption, run, hold }. `run` gets a small toolkit rather than
 * the raw page so the individual walkthroughs stay readable, and so every click goes through the
 * drawn cursor instead of happening invisibly.
 */
export async function record({ id, steps, seed, port, lead = 900, tail = 1600, posterAfter = 2 }) {
  mkdirSync(WORK, { recursive: true });
  mkdirSync(OUT, { recursive: true });
  const raw = join(WORK, id);
  rmSync(raw, { recursive: true, force: true });

  const browser = await chromium.launch({ executablePath: CHROME });
  const context = await browser.newContext({
    baseURL: `http://localhost:${port}`,
    viewport: SIZE,
    deviceScaleFactor: 1,
    recordVideo: { dir: raw, size: SIZE },
    // The walkthroughs demonstrate motion on purpose, so reduced-motion stays off here even though
    // the product honours it everywhere else.
    colorScheme: 'light',
  });
  const page = await context.newPage();

  // The caption in force right now. A step that navigates gets a brand new document with a brand
  // new empty overlay, which silently dropped the caption for the rest of that step — the viewer
  // saw a screen change with nothing telling them what they were looking at. Holding it here lets
  // `goto` repaint it on the other side.
  let current = null;

  const api = {
    page,
    /** Move the drawn cursor onto something and click it. */
    async click(selector, opts = {}) {
      const target = page.locator(selector).first();
      await target.waitFor({ state: 'visible', timeout: 15000 });
      await glideTo(page, selector);
      await tapMark(page);
      await target.click(opts);
      await page.waitForTimeout(260);
    },
    /** Type at a human rate so the viewer can read it going in. */
    async type(selector, text, delay = 42) {
      const target = page.locator(selector).first();
      await target.waitFor({ state: 'visible', timeout: 15000 });
      await glideTo(page, selector);
      await target.click();
      await target.type(text, { delay });
      await page.waitForTimeout(220);
    },
    async goto(path) {
      await page.goto(path, { waitUntil: 'networkidle' });
      await installOverlay(page);
      await paintCaption(page, current);
      await page.waitForTimeout(320);
    },
    async press(key) { await page.keyboard.press(key); await page.waitForTimeout(280); },
    async wait(ms) { await page.waitForTimeout(ms); },
    /** Ease down the page rather than jumping, so a viewer keeps their place. */
    async scrollTo(y, ms = 700) {
      await page.evaluate(({ y, ms }) => new Promise((done) => {
        const from = window.scrollY; const delta = y - from; const t0 = performance.now();
        const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2);
        const tick = (now) => {
          const t = Math.min(1, (now - t0) / ms);
          window.scrollTo(0, from + delta * ease(t));
          if (t < 1) requestAnimationFrame(tick); else done();
        };
        requestAnimationFrame(tick);
      }), { y, ms });
      await page.waitForTimeout(140);
    },
  };

  if (seed) await seed(page);
  await api.goto('/');

  const cues = [];
  const t0 = Date.now();
  const at = () => (Date.now() - t0) / 1000;

  await page.waitForTimeout(lead);

  for (const step of steps) {
    const start = at();
    if (step.caption) {
      current = { eyebrow: step.eyebrow || '', caption: step.caption };
      await paintCaption(page, current);
      // A beat to read the caption before anything moves under it.
      await page.waitForTimeout(Math.min(2400, 520 + step.caption.length * 26));
    }

    try {
      if (step.run) await step.run(api);
    } catch (err) {
      await context.close(); await browser.close();
      throw new Error(`[${id}] step "${step.caption || 'unnamed'}" failed: ${err.message}`);
    }

    if (step.hold) await page.waitForTimeout(step.hold);
    if (step.caption) cues.push({ start, end: at(), eyebrow: step.eyebrow || '', text: step.caption });

    // The poster frame, taken from inside the run rather than cut out of the finished file. The
    // bundled ffmpeg is a video-only build with no image encoder, and doing it here is better
    // anyway: it picks a deliberate moment — the product doing the thing — instead of whatever
    // happened to land on a timestamp. Without a poster, `preload="none"` shows a black rectangle,
    // and a grid of black rectangles reads as broken rather than as unplayed.
    if (cues.length === posterAfter) {
      await page.screenshot({ path: join(OUT, `${id}.jpg`), type: 'jpeg', quality: 72 }).catch(() => {});
    }
  }

  await page.evaluate(() => document.getElementById('vantage-cap')?.classList.remove('on'));
  await page.waitForTimeout(tail);

  await context.close();
  await browser.close();

  const produced = readdirSync(raw).filter((f) => f.endsWith('.webm'));
  if (!produced.length) throw new Error(`[${id}] playwright produced no video`);
  const src = join(raw, produced[0]);

  // Re-encode: the raw capture is ~190 KB/s, which is far more than a low-motion screencast needs
  // and far more than belongs in a git repository. VP8 is what the bundled ffmpeg has, and at this
  // bitrate it is visually indistinguishable on UI content.
  const dest = join(OUT, `${id}.webm`);
  const enc = spawnSync(FFMPEG, [
    '-hide_banner', '-loglevel', 'error', '-i', src,
    '-c:v', 'libvpx', '-b:v', '260k', '-crf', '33', '-g', '240',
    '-deadline', 'good', '-cpu-used', '2', '-an', dest, '-y',
  ], { encoding: 'utf8' });
  if (enc.status !== 0) {
    // Better a large correct file than no file: keep the raw capture rather than failing the run.
    renameSync(src, dest);
    console.warn(`[${id}] re-encode unavailable (${enc.stderr?.trim() || enc.error?.message}); kept the raw capture`);
  }

  writeFileSync(join(OUT, `${id}.vtt`),
    `WEBVTT\n\n${cues.map((c, i) =>
      `${i + 1}\n${vtt(c.start)} --> ${vtt(c.end)}\n${c.eyebrow ? `<v ${c.eyebrow}>` : ''}${c.text}\n`).join('\n')}`);

  rmSync(raw, { recursive: true, force: true });
  const kb = statSync(dest).size / 1024;
  const seconds = cues.length ? cues[cues.length - 1].end + tail / 1000 : 0;
  console.log(`  ${id}.webm  ${kb.toFixed(0)} KB  ${seconds.toFixed(0)}s  ${cues.length} captions`);
  return { id, kb, seconds };
}

/** Boots the app the same way the browser suite does: in-memory database, built client. */
export function startServer(port) {
  const srv = spawn('node', [join(ROOT, 'tests', 'browser', 'server.ts')], {
    cwd: ROOT,
    env: { ...process.env, VANTAGE_BROWSER_PORT: String(port) },
    stdio: 'ignore',
  });
  return srv;
}

export async function waitForServer(port, timeoutMs = 30000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`http://localhost:${port}/api/auth/setup`);
      if (res.ok) return;
    } catch { /* not up yet */ }
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error(`server did not come up on ${port}`);
}
