export const RANKS = [
  { grade: 'E-1', abbr: 'Pvt', name: 'Private', tier: 'enlisted', sort: 1 },
  { grade: 'E-2', abbr: 'PFC', name: 'Private First Class', tier: 'enlisted', sort: 2 },
  { grade: 'E-3', abbr: 'LCpl', name: 'Lance Corporal', tier: 'enlisted', sort: 3 },
  { grade: 'E-4', abbr: 'Cpl', name: 'Corporal', tier: 'nco', sort: 4 },
  { grade: 'E-5', abbr: 'Sgt', name: 'Sergeant', tier: 'nco', sort: 5 },
  { grade: 'E-6', abbr: 'SSgt', name: 'Staff Sergeant', tier: 'snco', sort: 6 },
  { grade: 'E-7', abbr: 'GySgt', name: 'Gunnery Sergeant', tier: 'snco', sort: 7 },
  { grade: 'E-8', abbr: 'MSgt', name: 'Master Sergeant', tier: 'snco', sort: 8 },
  { grade: 'E-8', abbr: '1stSgt', name: 'First Sergeant', tier: 'snco', sort: 9 },
  { grade: 'E-9', abbr: 'MGySgt', name: 'Master Gunnery Sergeant', tier: 'snco', sort: 10 },
  { grade: 'E-9', abbr: 'SgtMaj', name: 'Sergeant Major', tier: 'snco', sort: 11 },
  { grade: 'E-9', abbr: 'SMMC', name: 'Sergeant Major of the Marine Corps', tier: 'snco', sort: 12 },
  { grade: 'W-1', abbr: 'WO', name: 'Warrant Officer 1', tier: 'warrant', sort: 20 },
  { grade: 'W-2', abbr: 'CWO2', name: 'Chief Warrant Officer 2', tier: 'warrant', sort: 21 },
  { grade: 'W-3', abbr: 'CWO3', name: 'Chief Warrant Officer 3', tier: 'warrant', sort: 22 },
  { grade: 'W-4', abbr: 'CWO4', name: 'Chief Warrant Officer 4', tier: 'warrant', sort: 23 },
  { grade: 'W-5', abbr: 'CWO5', name: 'Chief Warrant Officer 5', tier: 'warrant', sort: 24 },
  { grade: 'O-1', abbr: '2ndLt', name: 'Second Lieutenant', tier: 'officer', sort: 30 },
  { grade: 'O-2', abbr: '1stLt', name: 'First Lieutenant', tier: 'officer', sort: 31 },
  { grade: 'O-3', abbr: 'Capt', name: 'Captain', tier: 'officer', sort: 32 },
  { grade: 'O-4', abbr: 'Maj', name: 'Major', tier: 'officer', sort: 33 },
  { grade: 'O-5', abbr: 'LtCol', name: 'Lieutenant Colonel', tier: 'officer', sort: 34 },
  { grade: 'O-6', abbr: 'Col', name: 'Colonel', tier: 'officer', sort: 35 },
  { grade: 'O-7', abbr: 'BGen', name: 'Brigadier General', tier: 'officer', sort: 36 },
  { grade: 'O-8', abbr: 'MajGen', name: 'Major General', tier: 'officer', sort: 37 },
  { grade: 'O-9', abbr: 'LtGen', name: 'Lieutenant General', tier: 'officer', sort: 38 },
  { grade: 'O-10', abbr: 'Gen', name: 'General', tier: 'officer', sort: 39 },
];
